conditioning:
  # No hard measurement constraint
  method: ddnm
  params:

data:
  name: lsun
  root: datasets/lsun_val

measurement:
  operator:
    name: nonlinear_blur
    opt_yml_path: bkse/options/generate_blur/default.yml

  noise: 
    name: gaussian
    sigma: 0.05